name: myxpenses
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  go_router: ^13.0.1
  uuid: ^4.1.0
  rxdart: ^0.27.7
  intl: ^0.19.0
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.19+1
  path_provider: ^2.1.2
  path: ^1.8.3
  sqlite3: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  mockito: ^5.4.4
  mock_data: ^2.0.1
  custom_lint: ^0.5.8
  riverpod_lint: ^2.3.7
  drift_dev: ^2.14.1

flutter:
  uses-material-design: true
