name: myxpenses
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  equatable: ^2.0.7
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3
  go_router: ^16.1.0
  uuid: ^4.5.1
  rxdart: ^0.28.0
  intl: ^0.20.2
  drift: ^2.28.1
  sqlite3_flutter_libs: ^0.5.39
  path_provider: ^2.1.5
  path: ^1.9.1
  sqlite3: ^2.9.0
  riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.5
  mockito: ^5.4.6
  mock_data: ^2.0.1
  custom_lint: ^0.7.6
  riverpod_lint: ^2.6.5
  drift_dev: ^2.28.0

flutter:
  uses-material-design: true
