name: myxpenses
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.4
  riverpod_annotation: ^2.2.1
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  go_router: ^12.0.1
  uuid: ^4.1.0
  rxdart: ^0.27.7
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.3
  mockito: ^5.4.2
  mock_data: ^2.0.1
  custom_lint: ^0.5.5
  riverpod_lint: ^2.1.1

flutter:
  uses-material-design: true
