// Mocks generated by Mockito 5.4.4 from annotations
// in myxpenses/test/expenses/presentation/create/create_expense.screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i2;
import 'package:go_router/go_router.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:myxpenses/core/presentation/navigation/app_router.dart' as _i4;
import 'package:myxpenses/expenses/data/expenses.repository.dart' as _i6;
import 'package:myxpenses/expenses/expenses.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRef_0<State extends Object?> extends _i1.SmartFake
    implements _i2.Ref<State> {
  _FakeRef_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGoRouter_1 extends _i1.SmartFake implements _i3.GoRouter {
  _FakeGoRouter_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AppRouter].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppRouter extends _i1.Mock implements _i4.AppRouter {
  MockAppRouter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Ref<Object?> get ref => (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeRef_0<Object?>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i2.Ref<Object?>);

  @override
  _i3.GoRouter get routerConfig => (super.noSuchMethod(
        Invocation.getter(#routerConfig),
        returnValue: _FakeGoRouter_1(
          this,
          Invocation.getter(#routerConfig),
        ),
      ) as _i3.GoRouter);

  @override
  void goBack() => super.noSuchMethod(
        Invocation.method(
          #goBack,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void goHome() => super.noSuchMethod(
        Invocation.method(
          #goHome,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void openCreateAccount() => super.noSuchMethod(
        Invocation.method(
          #openCreateAccount,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void openAccountDetails(String? accountId) => super.noSuchMethod(
        Invocation.method(
          #openAccountDetails,
          [accountId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void openEditAccount(String? accountId) => super.noSuchMethod(
        Invocation.method(
          #openEditAccount,
          [accountId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void openCreateExpense(String? accountId) => super.noSuchMethod(
        Invocation.method(
          #openCreateExpense,
          [accountId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void openEditExpense(_i5.ExpenseModel? expense) => super.noSuchMethod(
        Invocation.method(
          #openEditExpense,
          [expense],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ExpensesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpensesRepository extends _i1.Mock
    implements _i6.ExpensesRepository {
  MockExpensesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i5.ExpenseModel>> loadExpenses({
    required String? accountId,
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadExpenses,
          [],
          {
            #accountId: accountId,
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue:
            _i7.Future<List<_i5.ExpenseModel>>.value(<_i5.ExpenseModel>[]),
      ) as _i7.Future<List<_i5.ExpenseModel>>);

  @override
  _i7.Future<_i5.ExpenseModel?> loadExpense({required String? id}) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadExpense,
          [],
          {#id: id},
        ),
        returnValue: _i7.Future<_i5.ExpenseModel?>.value(),
      ) as _i7.Future<_i5.ExpenseModel?>);

  @override
  _i7.Future<void> insertExpense(_i5.ExpenseModel? expense) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertExpense,
          [expense],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateExpense(_i5.ExpenseModel? expense) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateExpense,
          [expense],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteExpense(_i5.ExpenseModel? expense) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteExpense,
          [expense],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteAllExpensesForAccount(String? accountId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAllExpensesForAccount,
          [accountId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}
