name: Flutter Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macOS-latest
    strategy:
      matrix:
        flutter-version: ['3.16.x','3.13.x']
    steps:
      - uses: actions/checkout@v4
  
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter-version }}
          channel: 'stable'
      
      - name: Run Flutter tests
        run: flutter test
